mod resolv;

pub use resolv::{
    MAXDNAME,
    MAXHOSTNAMELEN,
    NS_PACKETSZ,
    RES_DEBUG,
    RES_DEFAULT,
    RES_DEFNAMES,
    RES_DNSRCH,
    RES_IGNTC,
    RES_INIT,
    RES_NOALIASES,
    RES_NORELOAD,
    RES_NOTLDQUERY,
    RES_RECURSE,
    RES_ROTATE,
    RES_SNGLKUP,
    RES_SNGLKUPREOP,
    RES_STAYOPEN,
    RES_TRUSTAD,
    RES_USEVC,
    RES_USE_DNSSEC,
    RES_USE_EDNS0,
    __ns_sect_ns_s_an,
    __ns_sect_ns_s_ar,
    __ns_sect_ns_s_ns,
    __ns_sect_ns_s_qd,
    __res_ninit as res_ninit,
    __res_state,
    ns_initparse,
    ns_msg,
    ns_name_uncompress,
    ns_parserr,
    ns_rr,
    ns_sect,
    res_nquery,
    res_nsearch,
};
